### ISSUE TITLE
Upgrade Level Support for newest Edgar-DotNet

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/pmdungeon-old#10]
- https://github.com/OndrejNepozitek/Edgar-DotNet
- current support only for Version v1.0.6

**Comment by cagix** [comment]
**clean-up**: @AMatutat @Tobias321 Brauchen wir das noch und sollte das in die neuen Repos verschoben werden, oder kann das zu?

**Comment by AMatutat** [comment]
outdated
