### ISSUE TITLE
[QUESTION] Set this repo to read-only (archive)

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/pmdungeon-old#100]
Dieses Repo wird nicht mehr bewirtschaftet. Sollen wir es auf "Archive" setzen und damit einfrieren?

Vorteile: 
- Es steht dann einschließlich Historie zum Nachschlagen bereit (im Vergleich zum Löschen).
- Es wird nicht versehentlich hier nochmal was gepusht oder Tickets aufgemacht o.ä.

Nachteile:
- Wir sollten die Tickets durchgehen und entweder als "wontfix" schliessen oder in die neuen Repos verschieben
- Wir sollten die Pullrequests ansehen und überlegen, was davon wir in den neuen Repos gebrauchen könnten. Insbesondere die Systemtests von @CrappyAlgorithm sollten nicht verloren gehen und auf die neuen Repos übertragen werden!

@AMatutat @Tobias321 Was denkt ihr?

**Comment by AMatutat** [comment]
find ich gut.
Ich bin schonmal hinter dir hergegangen und hab geschlossen bzw. als wontfix markiert.

**Comment by AMatutat** [comment]
sorry ^^ finger wieder schneller als die augen

**Comment by cagix** [comment]
> > Insbesondere die Systemtests von @CrappyAlgorithm sollten nicht verloren gehen und auf die neuen Repos übertragen werden!
> 
> Die liegen im Branch `sebastian` oder?

keine Ahnung :)  ... aber das weisst sicher @CrappyAlgorithm selbst am besten?

**Comment by cagix** [comment]
> find ich gut. Ich bin schonmal hinter dir hergegangen und hab geschlossen bzw. als wontfix markiert.

ok, dann lass uns das so machen.

ich würde tatsächlich alle noch offenen (nicht gefixten) issues als "bug, wontfix" markieren und schließen. wir arbeiten ja nicht mehr dran. danach kann das ding auch "archive".

**Comment by AMatutat** [comment]
> Ich würde tatsächlich alle noch offenen (nicht gefixten) issues als "bug, wontfix" markieren und schließen

Hab noch dreimal drüber nachgedacht und bin jetzt auch bei dir.

**Comment by AMatutat** [comment]
Aus meiner Sicht:
- verweis auf neues Projekt noch in die Readme/Beschreibung
- dieses issue schließen
- archivieren

**Comment by cagix** [comment]
> Aus meiner Sicht:
> 
> * verweis auf neues Projekt noch in die Readme/Beschreibung
> * dieses issue schließen
> * archivieren

go ahead :)

**Comment by AMatutat** [comment]
Alle Leute raus, ich schließ ab.
