### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/pmdungeon-old#12]
LibGDX supports Android, so this framework should also

**Comment by cagix** [comment]
**clean-up**: @AMatutat @Tobias321 Brauchen wir das noch und sollte das in die neuen Repos verschoben werden, oder kann das zu?

**Comment by AMatutat** [comment]
könnte man mal in Angriff nehmen aber in Hinblick auf unsere Erfahrung mit HTML: dicht
