### ISSUE TITLE
Bug: image scaling

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/pmdungeon-old#21]
- some sprites get a wierd scaling 
- h/w = 2.1 -> Big Sword
- h/w = 1.75 -> Normal Hero

**Comment by AMatutat** [comment]
quick fix: 
add draw(offset,offset,scaleX,scaleY)

**Comment by cagix** [comment]
**clean-up**: @AMatutat @Tobias321 Brauchen wir das noch und sollte das in die neuen Repos verschoben werden, oder kann das zu?

**Comment by AMatutat** [comment]
ich würde es offen lassen und mit wontfix versehen. Falls jemand nochmal das alte Framework nutzt und auf den Fehler stößt, weiß er zumindest das es da einen gibt.

**Comment by cagix** [comment]
> ich würde es offen lassen und mit wontfix versehen. Falls jemand nochmal das alte Framework nutzt und auf den Fehler stößt, weiß er zumindest das es da einen gibt.

Wenn wir das Ding archivieren, sollten die Tickets zu sein -- ggf. mit "wontfix".

Die Frage ist aber: Ist das etwas, was unseren neuen Dungeon auch betreffen kann? Sollten wir das Ding als Remindes mit rüber nehmen?

**Comment by AMatutat** [comment]
> Die Frage ist aber: Ist das etwas, was unseren neuen Dungeon auch betreffen kann? Sollten wir das Ding als Remindes mit rüber nehmen?

Im neuen Dungeon haben wir das gefixt. Hing mit der Kameraperspektive zusammen (zumindest hab ich mir das so gemerkt).

**Comment by cagix** [comment]
ok, dann "bug+wontfix" und zu
