### ISSUE TITLE
open constants

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/pmdungeon-old#34]
the students should be able to alter some settings, including

- screen size
- fullscreen/windowmode
- FPS
- assets Path
- StartLevel 
- windowname
- resizeable

this should stay optional.

**Comment by Kushurando** [comment]
I need help from someone that understands Gradle

I have to dependencies, libgdx graphics, and the apache commons cli 1.4 I need to add to the script, but I honestly don't know how.

**Comment by cagix** [comment]
@Kushurando wrong issue? anyway, have a look at the current `build.gradle`, check the `dependencies` section ... you can add a dependency using a gradle snippet which you can get from maven central ...

**Comment by AMatutat** [comment]
@Kushurando just curious, why you need to add new dependencies? 
@cagix Though gradle is ready to run.

**Comment by Kushurando** [comment]
@AMatutat @cagix sorry about the wrong issue, I blame the heat :D 

I need the new dependencies for the launch variables, I used the commons cli die parse them, and the fullscreen mode, the current parts of libgdx that we have only suppport it via displaymode which is part of gdx.graphics, which is not part of the dependencies

Just copy pasting the string from mavencentral into dependencies didn't work out, I am not quite sure why

**Comment by cagix** [comment]
@Kushurando I'd suggest you to open a new problem, please. And please provide more details so we can reproduce the problem... ... I happen to be unable to find my divination sphere at the moment ;)

**Comment by Kushurando** [comment]
Actually just figured out my mistake, it's working now.

**Comment by cagix** [comment]
**clean-up**: @AMatutat @Tobias321 Brauchen wir das noch und sollte das in die neuen Repos verschoben werden, oder kann das zu?

**Comment by AMatutat** [comment]
brauchen, nein. Schade um die Arbeit aber wird nicht mehr benötigt.
