### ISSUE TITLE
Linux HUD 

### ISSUE THREAD

**Issue by timonBusch** [PM-Dungeon/pmdungeon-old#42]
HUD Feature funktioniert nicht auf Linux Mint 19

**Comment by AMatutat** [comment]
Maybe connected with #6

**Comment by cagix** [comment]
**clean-up**: @AMatutat @Tobias321 Brauchen wir das noch und sollte das in die neuen Repos verschoben werden, oder kann das zu?

**Comment by AMatutat** [comment]
ich würde es offen lassen und mit wontfix versehen. Falls jemand nochmal das alte Framework nutzt und auf den Fehler stößt, weiß er zumindest das es da einen gibt.

**Comment by cagix** [comment]
@AMatutat Die Frage ist, ob das auch für den neuen Dungeon relevant ist. Vermutlich ja, da wir immer noch auf libGDX aufsetzen und sich intern nicht sooo viel getan hat. Also: Sollten wir das Ding als Andenken mit rüber nehmen? Wir könnten es markieren als "geerbt"?

**Comment by cagix** [comment]
@AMatutat Und wenn wir das Repo hier archivieren, dann sollten die Tickets zu. Wenigstens als "wontfix".

**Comment by AMatutat** [comment]
> @AMatutat Die Frage ist, ob das auch für den neuen Dungeon relevant ist. Vermutlich ja, da wir immer noch auf libGDX aufsetzen und sich intern nicht sooo viel getan hat. Also: Sollten wir das Ding als Andenken mit rüber nehmen? Wir könnten es markieren als "geerbt"?

Ich tue mich schwer einen "BUG" mit rüber zu nehmen. Es wäre aber tatsächlich ein Issue wert, die Kompatibilität mit Linux/Mac noch einmal zu überprüfen.

**Comment by cagix** [comment]
> > @AMatutat Die Frage ist, ob das auch für den neuen Dungeon relevant ist. Vermutlich ja, da wir immer noch auf libGDX aufsetzen und sich intern nicht sooo viel getan hat. Also: Sollten wir das Ding als Andenken mit rüber nehmen? Wir könnten es markieren als "geerbt"?
> 
> Ich tue mich schwer einen "BUG" mit rüber zu nehmen. Es wäre aber tatsächlich ein Issue wert, die Kompatibilität mit Linux/Mac noch einmal zu überprüfen.

hast auch recht. vorschlag: mache drüben ein neues ticket auf und erwähne dieses hier (link kopieren). dann ist es hier als nicht gefixter bug vermerkt und drüben haben wir eine erinnerung, dass wir da nochmal genau hinschauen müssen.



> > Und wenn wir das Repo hier archivieren, dann sollten die Tickets zu. Wenigstens als "wontfix".
> 
> Ich hätte gesagt, alles was "Feature" ist machen wir dicht und was ein "Bug" ist lassen wir offen mit wontfix

ich würde die bugs alle mit "bug+wontfix" markieren und schließen. wir arbeiten ja hier nicht mehr dran. und wenn doch jemand sucht oder forkt, dann kann er ja gezielt nach "bug+wontfix" suchen und sich den spass reinziehen :)
