### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/pmdungeon-old#6]
Known problems
- application starts, but window is not visible. 

Open questions
- does the program realy run?

**Comment by cagix** [comment]
can confirm this issue. 

build w/ gradle works, all dependencies are downloaded and the application is started. however, a window does not appear. the task manager shows a java process that uses quite some cpu. there is no indication that a process was blocked. 

also occurs when starting via maven (see pr #38).

**Comment by RipDip** [comment]
I have tested on a macbook air and i can see the windows. With Eclipse I can start the game with and see the window.
I implement a basic game with the main and the hero from the readme. In the Arguments in -vm Argument i add -XstartOnFirstThread.
So the game work by me

**Comment by cagix** [comment]
@RipDip which version of macos? which jdk?

**Comment by cagix** [comment]
from https://libgdx.com/dev/setup/: > At the moment, libGDX projects do not work with JDK 16, as Gretty does not yet support Gradle 7. As a consequence, you are advised to use JDK 8-15!

**Comment by RipDip** [comment]
I use the High Sierra version 10.13.6 and the JDK is 15

**Comment by cagix** [comment]
hmmm, ok. i'm on 11.4 and 16 ... maybe thats the difference. strange.

**Comment by cagix** [comment]
**clean-up**: @AMatutat @Tobias321 Brauchen wir das noch und sollte das in die neuen Repos verschoben werden, oder kann das zu?

**Comment by AMatutat** [comment]
ich würde es offen lassen und mit wontfix versehen. Falls jemand nochmal das alte Framework nutzt und auf den Fehler stößt, weiß er zumindest das es da einen gibt.

**Comment by cagix** [comment]
@AMatutat auch hier: betrifft uns das nicht im neuen dungeon auch? das unterliegende framework ist doch immer noch das selbe. sollten wir es als potentielles problem mit rüber nehmen, evtl. als "not verified yet" markieren?

**Comment by cagix** [comment]
> @AMatutat auch hier: betrifft uns das nicht im neuen dungeon auch? das unterliegende framework ist doch immer noch das selbe. sollten wir es als potentielles problem mit rüber nehmen, evtl. als "not verified yet" markieren?

besser: mach mal drüben bitte ein neues ticket auf und kopieren dort den link auf dieses ticket mit rein.
