### ISSUE TITLE
Doc for Maven

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/pmdungeon-old#60]
for #58

**Comment by AMatutat** [comment]
This should be some sort of "Maven beginners guid"

**Comment by cagix** [comment]
**clean-up**: @AMatutat @Tobias321 Brauchen wir das noch und sollte das in die neuen Repos verschoben werden, oder kann das zu?

**Comment by AMatutat** [comment]
Maven ist tot, lang lebe Gradle.

**Comment by cagix** [comment]
> Maven ist tot, lang lebe Gradle.

@AMatutat Ich würde mal bezweifeln, das ein Industriestandard "tot" ist. Aber davon abgesehen, meine Frage war: Brauchen wir das drüben in den neuen Repos? 

Wir lehren auch Maven und mein Ziel ist bei all den tollen Gradle-Sachen, dass die Studis das sich auchm mit Maven zusammenbauen könnten. Also: Ist das ein Ticket für drüben?
