### ISSUE TITLE
update german manual

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/pmdungeon-old#66]
- remove old stuff
- fix inconsistencies
- grammar check

**Comment by AMatutat** [comment]
Use #71 for the new documentation structure.

**Comment by AMatutat** [comment]
also update image path

**Comment by cagix** [comment]
**clean-up**: @AMatutat @Tobias321 Brauchen wir das noch und sollte das in die neuen Repos verschoben werden, oder kann das zu?

**Comment by AMatutat** [comment]
legacy repo, no support.

**Comment by cagix** [comment]
> legacy repo, no support.

@AMatutat ja, das war klar. die frage war: brauchen wir das ticket noch, d.h. sollten wir es in die neuen repos transferieren?
